# Generated by Django 5.1.4 on 2025-05-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locatorapp', '0002_initial'),
    ]

    operations = [
    ]
