# Generated by Django 5.1.4 on 2025-05-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locatorapp', '0003_activitylog'),
        ('locatorapp', '0003_auto_20250515_2328'),
    ]

    operations = [
    ]
