# Generated by Django 5.1.4 on 2025-05-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ATM',
        ),
    ]
