CREATE TABLE banks (
    id INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    logo_url VARCHAR(255),
    website VARCHAR(255),
    contact_number VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);